(coq.theory
 (name proof_checker)
 (theories Stdlib
           mathcomp.ssreflect
           mathcomp.boot
           mathcomp.finite_group
           mathcomp.algebra
           mathcomp.order
           micromega_plugin
           elpi
           elpi_elpi
           HB
           dpdgraph)
 (flags -w -all))
