(* WARNING: This file is auto-generated by the parser package (v0.1.0.0).
   Do not modify this file directly. *)
From mathcomp Require Import all_ssreflect all_algebra.

Module ParsedCertificateSpecs.
  Definition n : nat := 57.
  Definition m : nat := 19.
End ParsedCertificateSpecs.
