module Generation (generateRocq, generateCertificateSpecs) where

import Data.List (intercalate)
import Data.Ratio (denominator, numerator)

import Parser
import Utils
import ProofTree
import Split

disclaimer :: String
disclaimer =
  "(* WARNING: This file is auto-generated by the parser package (v0.1.0.0).\n\
   \   Do not modify this file directly. *)"

generateRocq :: ProofCertificate -> ProofTree -> String
generateRocq cert proofTree =
  let n_val = length (lowerBounds cert)
      (Tableau rows) = tableau cert
      denseRows = map (\row -> tableauToList (n_val - 1) row) rows
  in disclaimer ++ "\n" ++ unlines
    [ "From mathcomp Require Import all_ssreflect all_algebra.",
      "Require Import certificate_specs.",
      "Require Import constraint.",
      "Require Import proof_tree.",
      "Require Import split.",
      "Require Import util.",

      "Import CertificateSpecs.",

      "Open Scope ring_scope.",
      "",
      "Module ParsedCertificates.",
      "",
      "  Definition lb : 'rV[R]_n :=",
      "    \\row_(j < n) (nth 0%R [:: " ++ intercalate "; " (map ratToString (lowerBounds cert)) ++ "] j).",
      "",
      "  Definition ub : 'rV[R]_n :=",
      "    \\row_(j < n) (nth 0%R [:: " ++ intercalate "; " (map ratToString (upperBounds cert)) ++ "] j).",
      "",
      "  Definition constraints : seq Constraint.t :=",
      "    [:: " ++ intercalate "; " (map constraintToRocq (constraints cert)) ++ " ].",
      "",
      "  Definition tableau : (m.+2).-tuple ('rV[R]_n) :=",
      "    [tuple nth (\\row_(j < n) 0%R) [::",
      intercalate ";\n" (map rowToRocq denseRows),
      "    ] i | i < m.+2].",
      "",
      "  Definition proof_tree : ProofTree.t :=",
      "    " ++ proofTreeToRocq proofTree ++ ".",
      "",
      "End ParsedCertificates."
    ]

ratToString :: Rational -> String
ratToString r =
  let n = numerator r
      d = denominator r
  in if d == 1
     then if n < 0 then "(" ++ show n ++ ")%R" else show n ++ "%:R"
     else if n < 0
          then "-(" ++ show (abs n) ++ " %:R / " ++ show d ++ " %:R)%R"
          else "(" ++ show n ++ " %:R / " ++ show d ++ " %:R)%R"

constraintToRocq :: Constraint -> String
constraintToRocq (Constraint _ vs) = case vs of
  (b : f : aux : _) ->
    "((inord " ++ show b ++ " : 'I_n), (inord " ++ show f ++ " : 'I_n), (inord " ++ show aux ++ " : 'I_n))"
  _ -> error "Constraint must have at least 3 variables"

rowToRocq :: [Rational] -> String
rowToRocq vals =
  "        \\row_(j < n) (nth 0%R [:: " ++ intercalate "; " (map ratToString vals) ++ "] j)"

proofTreeToRocq :: ProofTree -> String
proofTreeToRocq (Leaf xs) =
  "ProofTree.leaf [tuple nth 0%R [:: " ++ intercalate "; " (map ratToString xs) ++ "] i | i < m.+2]"
proofTreeToRocq (Node s l r) =
  "ProofTree.node (" ++ splitToRocq s ++ ")\n      ("
  ++ proofTreeToRocq l ++ ")\n      ("
  ++ proofTreeToRocq r ++ ")"

splitToRocq :: Split -> String
splitToRocq (SingleSplit v x) =
  "Split.single (inord " ++ show v ++ " : 'I_n) " ++ ratToString x
splitToRocq (ReluSplit b f aux) =
  "Split.relu (inord " ++ show b ++ " : 'I_n) (inord " ++ show f ++ " : 'I_n) (inord " ++ show aux ++ " : 'I_n)"

generateCertificateSpecs :: Int -> Int -> String
generateCertificateSpecs nVal mVal =
  disclaimer ++ "\n" ++ unlines
    [ "From mathcomp Require Import all_ssreflect all_algebra.",
      "",
      "Module ParsedCertificateSpecs.",
      "  Definition n : nat := " ++ show nVal ++ ".",
      "  Definition m : nat := " ++ show mVal ++ ".",
      "End ParsedCertificateSpecs."
    ]
